### PR TITLE
Feature/children ancestors odata

### PR DESCRIPTION
**Pull request by gallayl**
- Custom OData function to get children by Id
 - Custom OData function to get ancestors

### CODE REVIEW

**Comment by kavics** [comment]
I think this code can be better for walking upward:
```csharp
[ODataFunction]
public static IEnumerable<Content> Ancestors(Content content)
{
    var ancestors = new List<Content>();
    var ancestor = Content.Load(content.ContentHandler.ParentId);
    while (ancestor != null)
    {
        ancestors.Add(ancestor);
        ancestor = Content.Load(content.ContentHandler.ParentId);
    }
    return ancestors;
}
```

**Comment by gallayl** [comment]
I've improved the parent walk code based on the suggestions, however I've kept the try/catch block for now, I've got a SensenetSecurityExcepcion on the [Content.Load()](https://github.com/SenseNet/sensenet/blob/7a6afe5f63ba4389b827f91230f56e36f15ef556/src/ContentRepository/Tools.cs#L401) when I haven't got permission for the next parent.

**Comment by tusmester** [comment]
An even more compact solution for the parent walk:
```csharp
Content ancestor;
while ((ancestor = Content.Load(content.ContentHandler.ParentId)) != null)
    ancestors.Add(ancestor);
```
@kavics ?

**Comment by tusmester** [comment]
Other options for implementing this, instead of a _Children_ function:
- treat _/Children_ the same way as _/Actions_: a virtual field (see the _WriteContentProperty_ method)
- shortcut in ODataHandler.ProcessRequest: _WriteChildrenCollection_ if the property is _/Children_

These solutions would solve the problem of **autofilters** (url parameters).

**Pull request merged**
