### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sakshamtaneja21**
fixed typo

### CODE REVIEW

**Comment by sakshamtaneja21** [comment]
why did you make it invalid after merging it

**Comment by herflis** [comment]
I did not merged your pr, I’ve changed the base repository from master to develop and solved the conflicts.

**Comment by sakshamtaneja21** [comment]
ok

**Comment by sakshamtaneja21** [comment]
may i know the problem

**Comment by sakshamtaneja21** [comment]
how can I get an invite of your GitHub organization as a member

**Pull request closed without merging**
