### PR TITLE
Fixed invalid JSON

### LINKED ISSUE #773: Edit .settings files to be valid JSON
There are some .settings file in sensenet that contains invalid JSON value. We need to make sure that these values are valid JSON.

Here are the settings that need to be changed:

- https://github.com/SenseNet/sensenet/tree/master/src/nuget/snadmin/install-services/import/System/Settings
- https://github.com/SenseNet/sn-adsync/tree/master/src/nuget/snadmin/install-syncad2portal/import/System/Settings
- https://github.com/SenseNet/sn-preview/blob/master/src/Preview/nuget/snadmin/install-preview/import/System/Settings/DocumentPreview.settings

**Example for invalid JSON**
```json
{
  WatermarkEnabled: true,
  WatermarkFont: "Microsoft Sans Serif"
}
```
**Example for valid JSON**
```json
{
  "WatermarkEnabled": true,
  "WatermarkFont": "Microsoft Sans Serif"
}
```
Mind the double quotes around the key.

### PR DESCRIPTION
**Pull request by mikek2**
Closes #773 

Note: This commit only addresses the sensenet repo.

### CODE REVIEW

**Comment by herflis** [comment]
Hey @mikek2 , thanks for your contribution! 🙏 Don't forget to register 👉 [here](https://sensenet.com/Hacktoberfest2019) for the extra swag 👕

**Comment by B3zo0** [comment]
Hi @mikek2 thanks for your contribution. Can you please change the indention to 2 spaces please?

**Comment by mikek2** [comment]
Not a problem, @B3zo0.

I'll make a commit to address that later into the day, thank you!

**Comment by mikek2** [comment]
Changed indentation to 2 spaces!

**Pull request merged**
