### PR TITLE
Fix typos in code base

### PR DESCRIPTION
**Pull request by lex111**
I don’t know how important it is, but it safe to merge.

### CODE REVIEW

**Comment by lex111** [comment]
I found quite a lot of typos in the names of methods, properties, classes - I can fix them in separate PRs so that it is easier to revert changes, in which case possible errors, although this is a normal replacement, which should not affect the product.

Let me know if this needs to be done.

**Comment by tusmester** [comment]
Thank you for your contribution! I've pulled it into our dev branch, it will make into the next release.

**Comment by lex111** [comment]
So you changed the branch to `develop`! But for some reason, instead of accepting this PR, you created the same one. Very upset :(

image

**Comment by tusmester** [comment]
Hi @lex111 , sorry about this. I could not merge it directly into our dev branch, because it had conflicts with other commits. So I created a fix branch and pulled your changes there, made some changes and squash merged it to develop. And somewhere in this process the connection to the original PR has been lost. Again: sorry about that, it was definitely not intentional.
Does this mean that your PR has been removed from your hacktoberfest profile?

**Pull request closed without merging**
